name: "Donet Publish"

on:
  workflow_dispatch:
  release:
    types: [released, prereleased]

jobs:
  publish-it:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{github.token}}
    steps:
      - id: run
        run: |
          RUN_ID=$(gh api -XGET "/repos/${{github.repository}}/actions/workflows/dotnet-pack.yml/runs?branch=${{github.event.repository.default_branch}}&status=success&exclude_pull_requests=true&per_page=1" | jq -r '[.workflow_runs[]][0] | .id | .number')
          echo "LATEST_RUNID=$RUNID" >> $GITHUB_OUTPUT
          
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{steps.run.outputs.LATEST_RUNID}}
          github-token: ${{github.token}}
      - uses: actions/setup-dotnet@v4

      - run: |
          dotnet nuget add source --username ${{github.repository_owner}} --password $GH_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
          dotnet nuget push NUPKG/*.nupkg --api-key $GH_TOKEN --source "github"
      
      - if: ${{github.event_name == 'release'}}
        run: |
          gh release upload ${{ github.event.release.tag_name }} TSPKG/*.zip NUPKG/*.nupkg

      - name: Publishing to Thunderstore
        if: ${{github.event.release.prerelease == false}}
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_API_TOKEN }}
        run: |
          dotnet tcli publish --config-path TOML/*.toml --file TSPKG/*.zip
          
      