name: "Donet Publish"

on:
  workflow_dispatch:

jobs:
  publish-it:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
        - run: |
            RUNID=$(gh api repos/${{github.repository}}/commits/${{github.sha}}/check-runs) | jq -r '.check_runs[] | select(.name == "Package .NET") | .html_url | capture("/runs/(?<number>[0-9]+)/job") | .number' | sed 's/"//g' | head -n 1
            echo "$RUNID"