name: "Donet Publish"

on:
  workflow_dispatch:

jobs:
  publish-it:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
        - run: |
            RUNID=$(gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA/check-runs)
            echo "$RUNID"