name: "Donet Pack"

on:
  workflow_dispatch:
  push:

jobs:
  pack-it-up:
    if: github.event.repository.is_template == false && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    name: Package .NET
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{github.token}}
    
    steps:
      - name: Full Repository Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Build & Package
        id: run
        run: |
          dotnet pack --configuration Release | tee output.log
          last_line=$(tail -n 1 output.log)
          echo "last_line=$last_line" >> $GITHUB_OUTPUT
      - name: Format Build Output
        id: files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            var pkgs = ("${{steps.run.outputs.last_line}}").split(';');
            if (pkgs.length >= 1) {
              core.setOutput('NUPKG', pkgs[0]);
            }
            if (pkgs.length >= 2) {
              core.setOutput('TSPKG', pkgs[1]);
            }
            if (pkgs.length >= 3) {
              core.setOutput('TOML', pkgs[2]);
            }
      - uses: actions/upload-artifact@v4
        with:
          name: NUPKG
          path: ${{steps.files.outputs.NUPKG}}
      - uses: actions/upload-artifact@v4
        with:
          name: TSPKG
          path: ${{steps.files.outputs.TSPKG}}
      - uses: actions/upload-artifact@v4
        with:
          name: TOML
          path: ${{steps.files.outputs.TOML}}

      - name: Check If vars.PACKAGE_RUNID Exists
        id: check_var
        run: |
          gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{github.repository}}/actions/variables | grep '"name": "MY_VARIABLE"'
        continue-on-error: true
      
      - name: Create vars.PACKAGE_RUNID
        if: ${{ failure() }}
        run: |
          gh api --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{github.repository}}/actions/variables \
            -f name="PACKAGE_RUNID" -f value="${{github.run_id}}"
      
      - name: Update vars.PACKAGE_RUNID
        if: ${{ success() }}
        run: |
          gh api --method PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{github.repository}}/actions/variables/PACKAGE_RUNID \
            -f name="PACKAGE_RUNID" -f value="${{github.run_id}}"
 