name: "Donet Pack"

on:
  workflow_dispatch:
  push:

jobs:
  pack-it-up:
    if: github.event.repository.is_template == false && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    name: Package .NET
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-dotnet@v4
      - id: run
        run: |
          echo "last_line=$(dotnet pack --configuration Release | tee /dev/tty | tail -n 1)" >> $GITHUB_OUTPUT
      - name: Files As Array
        id: files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            let pkgs = "${{steps.run.outputs.last_line}}".split(';');
            if pkgs.length >= 1:
              core.setOutput('NUPKG', pkgs[0]);
            if pkgs.length >= 2:
              core.setOutput('TSPKG', pkgs[1]);
      - uses: actions/upload-artifact@v4
        with:
          name: NUPKG
          path: ${{steps.files.outputs.NUPKG}}
      - uses: actions/upload-artifact@v4
        with:
          name: TSPKG
          path: ${{steps.files.outputs.TSPKG}}
