name: Organization Template Updates

on:
  push:
    branches:
      - 'main'

jobs:
  get-repositories:
    name: Organization Repositories
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.org-grab.outputs.result }}
    steps:
      - name: Get Organization Data
        id: org-grab
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            var request = await github.request(`GET ${context.payload.organization.repos_url.replace('https://api.github.com', '')}`);
            if (request.status != 200)
              throw new Exception('Bad API response: ' + request.status);

            var repos = (await Promise.all(
              request.data.map(async i => await github.rest.repos.get({
                  owner: i.owner.login, repo: i.name
                })))).map(i => i.data).filter(i => !i.archived && !i.private && i.template_repository != null);
            return repos;

  update-matrix:
    name: Update Matrix
    needs: get-repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-repo: ${{ fromJson(needs.get-repositories.outputs.repositories) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.target-repo.full_name }}
          ref: ${{ github.event.repository.default_branch }}

             
