name: Organization Template Updates

on:
  push:
    branches:
      - 'main'

jobs:
  get-repositories:
    name: Organization Repositories
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.org-grab.outputs.result }}
    env:
      this_repo: ${{ github.repository }}
    steps:
      - name: Get Organization Data
        id: org-grab
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            var request = await github.request(`GET ${context.payload.organization.repos_url.replace('https://api.github.com', '')}`);
            if (request.status != 200)
              throw new Exception('Bad API response: ' + request.status);

            var repos = (await Promise.all(
              request.data.map(async i => await github.rest.repos.get({
                  owner: i.owner.login, repo: i.name
                })))).map(i => i.data)
                .filter(i => !i.archived && !i.private && 
                        i.template_repository != null && i.template_repository.full_name == process.env.this_repo);
            return repos;

  update-matrix:
    name: Update ${{ matrix.target-repo.full_name }}
    needs: get-repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-repo: ${{ fromJson(needs.get-repositories.outputs.repositories) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.target-repo.full_name }}
          ref: ${{ github.event.repository.default_branch }}

      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Merge Remote
        id: merge
        env:
          PR_BRANCH: updated/template/${{ matrix.target-repo.name }}
          REMOTE_FULLNAME: ${{ matrix.target-repo.full_name }}
          REMOTE_DEFAULT_BRANCH: ${{ matrix.target-repo.default_branch }}
        run: |
          git checkout ${{ env.PR_BRANCH }} 2>/dev/null || git checkout -b ${{ env.PR_BRANCH }}
          git remote add ${{ env.REMOTE_FULLNAME }} https://github.com/${{ env.REMOTE_FULLNAME }}.git
          git fetch ${{ env.REMOTE_FULLNAME }} ${{ env.REMOTE_DEFAULT_BRANCH}}
          git merge -X theirs --allow-unrelated-histories ${{ env.REMOTE_FULLNAME }}/${{ env.REMOTE_DEFAULT_BRANCH}}

          echo 'GIT_DIFF<<EOF' >> $GITHUB_OUTPUT
          git diff ${{ env.PR_BRANCH }} ${{ env.REMOTE_FULLNAME }}/${{ env.REMOTE_DEFAULT_BRANCH}} >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          
      - env:
          DIFF: ${{ steps.merge.outputs.GIT_DIFF }}
        run: cat $DIFF
