name: Organization Template Updates

on:
  push:
    branches:
      - 'main'

jobs:
  get-repositories:
    name: Organization Repositories
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.org-grab.outputs.result }}
    steps:
      - name: Get Organization Data
        id: org-grab
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            var request = await github.request(`GET ${context.payload.organization.repos_url.replace('https://api.github.com', '')}`);
            if (request.status != 200)
              throw new Exception('Bad API response: ' + request.status);

            var repos = request.data.filter(i => !i.archived && !i.private).map(i => i.full_name);
            console.log(request.data.filter(i => !i.archived && !i.private).map(i => await github.rest.repos.get({
              owner: i.owner.login, repo: i.name
            })));
            return repos;
             
